name: Require Checklist

on:
  pull_request:
    types: [opened, edited, synchronize]
  workflow_call:

jobs:
  require-checklist:
    runs-on: ubuntu-latest
    name: Require Checklist
    steps:
      - uses: mheap/require-checklist-action@v2
        with:
          requireChecklist: true
