name: Verify issue

on:
  pull_request:
    types: [edited, synchronize, opened, reopened]
  check_run:
  workflow_call:
    secrets:
      ORG_PAT:
        required: true

jobs:
  verify_linked_issue:
    runs-on: ubuntu-latest
    name: Ensure Pull Request has a linked issue.
    steps:
      - name: Verify Linked Issue
        uses: hattan/verify-linked-issue-action@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PAT }}
        with:
          message: |
            ### 🚨 Action Required: Missing Issue Link

            We couldn't find an issue linked to this Pull Request. 

            **How to fix this:**
            Please edit your PR description and add a reference to the related issue using a keyword. 
            > Example: `Closes #123` or `Fixes #123`