name: "Verify issue"

on:
  pull_request:
    types: [edited, synchronize, opened, reopened]
  check_run:

jobs:
  verify_linked_issue:
    runs-on: ubuntu-latest
    name: Ensure Pull Request has a linked issue.
    steps:
      - name: Verify Linked Issue
        uses: hattan/verify-linked-issue-action@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PAT }}
        with:
          message: "Error: No issue is linked to this Pull Request. Please link an issue by adding a reference (e.g., 'Closes #123') to the PR description."
