name: Require Checklist

on:
  workflow_call:

jobs:
  require-checklist:
    runs-on: ubuntu-latest
    name: Require Checklist
    steps:
      - uses: mheap/require-checklist-action@v2
        with:
          requireChecklist: true
