name: "Reusable - Pre-commit (Node)"

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: "24"

jobs:
  pre-commit:
    name: "Pre-commit Checks (Node)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
      - run: npm ci

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
