name: "Reusable - Label PR on Failure"

on:
  workflow_call:

jobs:
  add-label:
    name: "Add 'to fix' label"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add "to fix" label
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} \
            --add-label "to fix" \
            --repo ${{ github.repository }}
